### PR TITLE
Add --no-figlet-y-offset.

### PR DESCRIPTION
**Pull request by shlomif**
To put the unadorned text at the top or bottom or wherever.

"I love it when a plan comes together" --
https://en.wikipedia.org/wiki/I_love_it_when_a_plan_comes_together

---

I hereby disclaim any implicit or explicit ownership of my changes in this
changeset, and put them under a multiple licence consisting of your choice of
one of more of:

- The CC0 / Public Domain - https://creativecommons.org/choose/zero/ .

- The MIT / Expat license - https://en.wikipedia.org/wiki/MIT_License

- The default licence of your project

- The https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License - version
2.1 or higher

- The https://en.wikipedia.org/wiki/GNU_General_Public_License - version 2 or
higher

- Any licence in the 2018-Aug-27 popular licenses list of
https://opensource.org/licenses

- The https://en.wikipedia.org/wiki/Apache_License version 2.0 or later

- The https://en.wikipedia.org/wiki/Artistic_License version 2.0 or later

- The https://en.wikipedia.org/wiki/ISC_license

- The https://opensource.org/licenses/BSD-2-Clause

Crediting me will be nice, but not mandatory, and you can change the licence
of the project without needing my permission.

### CODE REVIEW

**Comment by trehn** [comment]
Sorry, but this seems a bit niche. What do you want it for?

**Comment by shlomif** [comment]
> Sorry, but this seems a bit niche. What do you want it for?

When I use termdown inside a terminal window (e.g: [konsole](https://konsole.kde.org/) or [xterm](https://invisible-island.net/xterm/) ), then the fact that it puts the no-figlet text at the centre of the window makes it harder to keep seeing the clock's text in a visible place while putting other GUI windows on top of the terminal window. So I'd prefer to have it closer to the edge of the console.

Hope that helps, and thanks for your time.

**Comment by canyon289** [comment]
@trehn First off thank you for this awesome program. Its been very handy when teaching as a timer for "Time left in exercise" and @shlomif appreciate you contriburing to open source as well.

FWIW I would welcome a feature to position the timer at the top or bottom as well.

Again thank you both!

**Comment by shlomif** [comment]
On Sun, 12 Apr 2020 14:40:34 -0700
Ravin Kumar <notifications@github.com> wrote:

> @trehn First off thank you for this awesome program. Its been very handy when
> teaching as a timer for "Time left in exercise" and @shlomif appreciate you
> contriburing to open source as well.
> 
> FWIW I would welcome a feature to position the timer at the top or bottom as
> well.
> 
> Again thank you both!
> 

You're welcome, Ravin, and thanks for voicing your opinion!

-- @shlomif

-- 

Shlomi Fish       https://www.shlomifish.org/
Beginners Site for the Vim text editor - https://vim.begin-site.org/

Do one thing every day that scares you.
    — Eleanor Roosevelt

Please reply to list if it's a mailing list post - https://shlom.in/reply .

**Comment by trehn** [comment]
Okay, thank you!

**Comment by shlomif** [comment]
@trehn : you're welcome, and thanks for merging it!

**Pull request merged**
